### ISSUE TITLE
Work out how policies are implemented and what Terraform is doing

### ISSUE THREAD

**Issue by adamnovak** [ucsc-cgp/cgp-cloud-policies#4]
On the meeting today, Richard wanted to know what exactly Cloud Custodian was doing for us if we were just compiling it to Terraform, and I expressed disbelief that we would be compiling it to Terraform.

It looks like the actual answer might be that we aren't quite compiling it into Terraform, but we are replacing a bunch of its internal ability to deploy itself, and the `custodian` tool, with the Terraform generator code that in turn imports and calls a bunch of Cloud Custodian functions.

First we import enough of Cloud Custodian that we can read and understand its policies:

https://github.com/ucsc-cgp/cgp-cloud-policies/blob/98af127a21082fe68d8b38b85d58956348c1ac8a/scripts/c7n-terraform.py#L24-L33

Then we ask Cloud Custodian what kind of AWS resources it needs to make to implement the policy. We dispatch on the only type we support (policies that become cloud config rules) via this table:

https://github.com/ucsc-cgp/cgp-cloud-policies/blob/98af127a21082fe68d8b38b85d58956348c1ac8a/scripts/c7n-terraform.py#L224-L226

For some reason we break up generating the config rule and the lambda; they both ultimately come from the Cloud Custodian `mu` module, which has the type that Cloud Custodian uses to represent the lambdas it wants to build and the rules it wants to use to invoke them:

https://github.com/cloud-custodian/cloud-custodian/blob/1830fe4b9a59ff6afb675985c9ea531571616a76/c7n/mu.py#L813-L815

We let Cloud Custodian write a lambda function, and we then zip it up and try to write Terraform that will upload it and attach it to the config rule that Cloud Custodian asked for.

So it's not as bad as compiling Cloud Custodian policies to Terraform by ourselves would be, but we have ripped out/replaced a big chunk of Cloud Custodian's functionality, and I'm not sure how maintainable that will be. As soon as Cloud Custodian refactors `mu` and e.g. [replacing the lambda object's ARN with a Terraform variable](https://github.com/ucsc-cgp/cgp-cloud-policies/blob/98af127a21082fe68d8b38b85d58956348c1ac8a/scripts/c7n-terraform.py#L109) stops working, our system will break. As soon as we write a Cloud Custodian policy that wants to render down to something other than a Cloud Config rule with a lambda attached to it, we'll hit an unimplemented case in our renderer.

We might be best off fleshing this out into a real render-to-Terraform feature that we upstream to Cloud Custodian, to make maintenance in response to their refactorings their problem. Or, perhaps the features of the Cloud Custodian module we rely on are actually a stable public API that they guarantee support for. 

But if we end up ripping part of this out, I think it has to be the render-to-Terraform piece, which the README already contamplates skipping, and not the Cloud Custodian piece, because Cloud Custodian is doing all the work of writing the lambda functions that will enforce/react to violations of the policies.

**Comment by Richard-Hansen** [comment]
Functionality has been updated, see #5 for more details.
